### ISSUE TITLE
Missing ath10k firmware

### ISSUE THREAD

**Issue by tmshlvck** [tmshlvck/omnia-debian#1]
The resulting image does not contain ath10k firmware.

I have tested only the 10.2.4.70.54 from https://github.com/kvalo/ath10k-firmware.git and it does not work with all the channels that should be accessible in the regdomain set by iw reg set CZ:

```
iw list
...
Frequencies:
                        * 5180 MHz [36] (17.0 dBm)
                        * 5200 MHz [40] (17.0 dBm)
                        * 5220 MHz [44] (17.0 dBm)
                        * 5240 MHz [48] (17.0 dBm)
                        * 5260 MHz [52] (20.0 dBm) (no IR, radar detection)
                          DFS state: usable (for 4036 sec)
                          DFS CAC time: 60000 ms
                        * 5280 MHz [56] (20.0 dBm) (no IR, radar detection)
                          DFS state: usable (for 4036 sec)
                          DFS CAC time: 60000 ms
                        * 5300 MHz [60] (20.0 dBm) (no IR, radar detection)
                          DFS state: usable (for 4036 sec)
                          DFS CAC time: 60000 ms
                        * 5320 MHz [64] (20.0 dBm) (no IR, radar detection)
                          DFS state: usable (for 4036 sec)
                          DFS CAC time: 60000 ms
                        * 5500 MHz [100] (disabled)
                        * 5520 MHz [104] (disabled)
                        * 5540 MHz [108] (disabled)
                        * 5560 MHz [112] (disabled)
                        * 5580 MHz [116] (disabled)
                        * 5600 MHz [120] (disabled)
                        * 5620 MHz [124] (disabled)
                        * 5640 MHz [128] (disabled)
                        * 5660 MHz [132] (disabled)
                        * 5680 MHz [136] (disabled)
                        * 5700 MHz [140] (disabled)
                        * 5720 MHz [144] (disabled)
                        * 5745 MHz [149] (disabled)
                        * 5765 MHz [153] (disabled)
                        * 5785 MHz [157] (disabled)
                        * 5805 MHz [161] (disabled)
                        * 5825 MHz [165] (disabled)
```

Even though following frequencies should be accessible:

```
country CZ: DFS-ETSI
        (2400 - 2483 @ 40), (N/A, 20), (N/A)
        (5150 - 5250 @ 80), (N/A, 23), (N/A), NO-OUTDOOR
        (5250 - 5350 @ 80), (N/A, 20), (0 ms), NO-OUTDOOR, DFS
        (5470 - 5725 @ 160), (N/A, 26), (0 ms), DFS
        (57000 - 66000 @ 2160), (N/A, 40), (N/A)
```

Anybody knows what to do?

**Comment by d4nys3k** [comment]
Basically, setting ` REGDOMAIN=CZ` in /etc/default/crda should help. But it seems it doesn't work in Jessie for some reason, it can be fixed by using `wireless-regdb` package (version 2015.07.20-1) from Stretch. It's safe to upgrade this package.

After regdb upgrading, outdoor 5GHz frequencies are normally usable as expected with (our) CZ regdomain. I can't explain why, as from regdbdump there's no difference. 

Tested with `firmware-atheros` .deb package from Jessie backports (where's required firmware already included, there's no need to download firmware manualy). Backports are required in this case (firmware-atheros from Jessie doesn't contain required firmware binary)

**Comment by tmshlvck** [comment]
It seems that this issue reappeared in Buster and perhaps the same applies to Bullseye - we use stock Debian kernel and it seems that upstream made setting the regdomain for ath10k even more complicated: https://forums.debian.net//viewtopic.php?f=5&t=141402

Testing is needed.

**Comment by tmshlvck** [comment]
This is a mix of two issues - missing firmware has been resolved long time ago.

There are many MiniPCIe cards that have 0x00 country code set in EPROM which causes many channels to go disabled or no-IR (= can not be used in AP mode). There is an excellent description of the issue here https://github.com/pcengines/apu2-documentation/issues/189

With the current (Bookworm) kernel the ath10k works but the cards with wrong country code in EPROM are limited to wrong set of channels. This looks promissing: https://github.com/AndreySV/ath_regdm_patcher

**Comment by tmshlvck** [comment]
Closing this now as the original issue is resolved and the regdomain issue is off-topic here and it affects only cards with wrong EPROM settings.
