### ISSUE TITLE
Short layer2 loop after boot

### ISSUE THREAD

**Issue by d4nys3k** [tmshlvck/omnia-debian#4]
During boot, there's short layer 2 loop introduced by network configuration. Loop is caused by software bridge configured between eth0 and eth2 on system (standard Debian-way of bridge configuration), but built-in ethernet switch is initialised later (in rc.local), which splits eth0 and eth2 into separate VLANs (as origina Turris firmware does). 

Bridge should be enabled after switch configuration to eliminate this problem (can be, for example done by calling pre-up script of bridge interface). It's fine to initialize switch after eth0 is up (as this is control interface of MV88E6176 switch)

**Comment by tmshlvck** [comment]
Yes, you are right. I'll fix this by a pre-up script.

In fact I hope for quick resolution of problems in DSA driver for the 88E6176 switch which should replace the existing proprietary driver & swconfig utility that integrates into Debian really badly.

**Comment by tmshlvck** [comment]
Fixed in b6ee278c1159c6f139f2aab625a28fae2d408930.
