### ISSUE TITLE
create-kernel.sh refers to non-existing omnia-upstream branch in https://github.com/tmshlvck/omnia-linux.git

### ISSUE THREAD

**Issue by sdelafond** [tmshlvck/omnia-debian#5]

**Comment by tmshlvck** [comment]
My bad... Updated, re-tested, pushed.

Thanks for the report.

Btw. the master branch of this repo uses almost-upstream kernel (4.10-rc*). If you want 4.4 kernel, that is fairly close to TurrisOS kernel, please use stable branch.

**Comment by sdelafond** [comment]
Thanks a lot for the quick turnaround; BTW, I meant to ask, why are you choosing to base your Debian port on 4.10 instead of re-using the official TurrisOS kernel ? We can have this discussion someplace else I guess :)

**Comment by tmshlvck** [comment]
Yes, maybe I should rename my branches. Basically what is stable should be probably master. And the current master should be renamed to experimental.

I have basically the 4.10 kernel for experiments with DSA switch driver, which seems to be the better option than OpenWRT switch driver & swconfig util.

I'll rename the branches. It is indeed too confusing, when I think about it. Sorry...

**Comment by sdelafond** [comment]
I see, didn't notice the switch thing... I guess renaming will help, possibly even more if you include either the upstream kernel version you target and/or a reference to TurrisOS, something like master -> linux-4.10, stable -> turrisos-4.4
