### ISSUE TITLE
DTB not being included when running create-medkit.sh

### ISSUE THREAD

**Issue by tonikasch** [tmshlvck/omnia-debian#7]
The script create-medkit.sh runs create-kernel.sh which downloads a git kernel tree, builds it and generates two .deb packages with kernel image and kernel headers in the omnia-debian directory.

You can try this:

1. install working image

2. compile your own kernel - please see create-kernel.sh, if you want to change the kernel configuration you just need to run make menuconfig before the final make-kpkg, so it is easy to change.

3. take the .deb packages containing the kernel to the running omnia, create a btrfs snapshot (you may use "schnapps create" command) and then install the new kernel.

4. please check whether the new kernel installed and whether there is dtb file, something like /usr/lib/linux-image-4.4.0-08588-gebca056-dirty/armada-385-turris-omnia.dtb (the actual path depends on your kernel version).

And there should be a link /boot/dtb pointing towards the armada-385-turris-omnia.dtb file. If it is not, you can try to re-run script /etc/kernel/postinst.d/omnia-gen-bootlink or create the link manually (and point it to the dtb file from the older kernel, which should work anyway).

5) try to boot, if it fails you may roll back to the previous snapshot using the long reset button push (wait for two LEDs to light and then release the button).

**Comment by tmshlvck** [comment]
It is no longer an issue with Buster (which had the DTBs included in the deb packages) and Bullseye (which uses stock Debian kernel and just need a custom script to create boot.scr U-Boot script to load the right files).
